nautobot_ssot/jobs/base.py
Due to a behavioral quirk (bug?) in diffsync, a DIffSync adapter that contains no data will evaluate as falsey:
```python
>>> diffsync = DiffSync()
>>> bool(diffsync)
False
>>> diffsync.add(DiffSyncModel())
>>> bool(diffsync)
True
```
Change the checks that we have on the existence of the two adapters to explicit `is not None` checks to bypass this behavior.
=> Avoid skipping the diff and sync if one of the adapters is empty

nautobot_ssot/templatetags/humanize_bytes.py
Handle wrong input type for `humanize_bytes` filter function
This mitigates #39
=> Handle wrong input type for humanize_bytes filter

nautobot_ssot/templatetags/render_diff.py, nautobot_ssot/tests/test_render_diff.py
=> Escape dictionary curly bracket before renderingin HTML

.github/workflows/ci.yml, development/Dockerfile, development/nautobot_config.py, nautobot_ssot/__init__.py, nautobot_ssot/jobs/base.py, nautobot_ssot/jobs/examples.py, nautobot_ssot/tests/__init__.py, nautobot_ssot/tests/jobs/__init__.py, nautobot_ssot/tests/test_jobs.py, nautobot_ssot/tests/test_views.py, poetry.lock, pyproject.toml, tasks.py
Dropping Python3.6 support. 
- Several packages have already dropped the support for end of support Python 3.6
- Believe this may be causing other SSOT plugins to still be doing a Python3.6 container image (and thus only i386 containers)
=> Drops Python 3.6 Support

nautobot_ssot/forms.py, nautobot_ssot/views.py
Addresses issue #92 
This PR resolve two possible `out of sort memory` errors when running against a MySQL databse.
1. Navigating to `Plugins > Single Source of Truth > Dashboard`
2. Navigating to `Plugins > Single Source of Truth > Logs`
Additionally, the page load time is significantly faster.
=> fix-92: Defer loading JSONField 'diff' in queryset

.bandit.yml, mkdocs.yml, nautobot_ssot/migrations/0001_initial.py, nautobot_ssot/migrations/0002_performance_metrics.py, nautobot_ssot/migrations/0003_alter_synclogentry_textfields.py, nautobot_ssot/migrations/0004_sync_summary.py, poetry.lock, pyproject.toml
This PR is just to align the Prometheus client version with Nautobot. I also noticed that the RTD was missing the link update for release notes for v1.3 so I've fixed that too.
=> Fix Prometheus Dependency

nautobot_ssot/jobs/examples.py
I noticed example source job is failing now when I start with empty DB, providing PR that fixes that.
- Fixed to use "active" status as a fallback for missing status in example data source.
=> fix: Do not fail example data source job with invalid data

docs/admin/compatibility_matrix.md, docs/admin/release_notes/version_2.0.md, pyproject.toml
This PR is to prepare for the beta2 release for 2.0.0.
=> Release 2.0.0-beta.2

.github/workflows/ci.yml, development/Dockerfile, nautobot_ssot/forms.py, nautobot_ssot/integrations/aristacv/constant.py, nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py, nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py, nautobot_ssot/integrations/aristacv/signals.py, nautobot_ssot/integrations/aristacv/utils/cloudvision.py, nautobot_ssot/integrations/servicenow/models.py, nautobot_ssot/models.py, nautobot_ssot/tests/aristacv/fixtures/get_devices_response.json, nautobot_ssot/tests/aristacv/test_utils_cloudvision.py, poetry.lock, pyproject.toml
This PR is for updating the 2.0 branch to support Nautobot 2.0.0rc1. I found a few instances where slug was still in use for Platform and Status so I've corrected those and associated tests.
=> Update for Nautobot 2.0.0.rc1 Support

.github/workflows/ci.yml, nautobot_ssot/jobs/__init__.py, nautobot_ssot/jobs/base.py, nautobot_ssot/models.py, nautobot_ssot/templates/nautobot_ssot/dashboard.html, nautobot_ssot/templates/nautobot_ssot/data_source_target.html, nautobot_ssot/templatetags/dashboard_helpers.py, nautobot_ssot/tests/test_models.py, nautobot_ssot/tests/test_views.py, nautobot_ssot/views.py, poetry.lock, pyproject.toml
This PR is for updating the project to support Nautobot 2.0.0rc2. There were a few tweaks required for the UI to work and a tweak to the get_target/source_url functions as the Job class_path was moved to the JobResult. Also fixed the tests that were failing.
=> Enable RC2 Support

nautobot_ssot/integrations/aristacv/utils/cloudvision.py, nautobot_ssot/tests/aristacv/test_utils_cloudvision.py
[This](https://github.com/nautobot/nautobot-plugin-ssot-arista-cloudvision/pull/164) was the PR from the child repo.
=> Migrate PR #164 from Arista Child Repo

nautobot_ssot/integrations/infoblox/diffsync/adapters/infoblox.py, nautobot_ssot/integrations/infoblox/utils/client.py
This PR addresses the bug in #241 for the ltm-1.6 branch.
=> Fix Infoblox import_subnet for ltm-1.6

nautobot_ssot/metrics.py
=> fixes possible error state in nautobot_ssot_duration_seconds metric

nautobot_ssot/jobs/__init__.py, nautobot_ssot/metrics.py
We were told through the public Slack that the issue detailed in #248 is still occurring but at a different part of the code. I've added the same check that is done for the `metric_ssot_jobs()` function to the `metric_sync_operations()` and `metric_memory_usage()`. This should hopefully fix the issue now.
=> Add check for missing job_class attribute on 1.x Jobs

nautobot_ssot/contrib.py
One important note is that instead of the custom field `label` being used, I used the `key` to make it work. Using the label creates a different custom field that isn't registered and then will start throwing out warnings that the the target object doesn't have that field.
=> add fix for issue #257

nautobot_ssot/integrations/aristacv/jobs.py
This PR includes the fix for the dry-run issues brought up in #266. Both Jobs were missing run() definition for 2.0 so Job options weren't being passed to the parent Job or other parts of the code for required functionality. Now with this in place the dry-run, debug, and memory profiling options should all work in the CloudVision SSoT integration.
=> Fix CloudVision SSoT Jobs

docs/dev/jobs.md, nautobot_ssot/contrib.py
Problem:
As it currently stands, trying to sync the `time_zone` field in `Location` objects from Nautobot does not appear to be supported.
- Loading objects from the database returns a `DstTzInfo` object
- `DstTzInfo` is not JSON serializable and raises an error when used, so cannot be used for SSoT
- Unable to determine existing way to convert the `DstTzInfo` object into a string which can be compared within SSoT
- Unable to override an individual field when loading from the Nautobot adapter
Solution:
This PR provides two solutions:
1. A way for any child class of `NautobotAdapter` to add additional methods to override the default loading of individual fields/parameters (excluding custom fields and relationships). It searches for a method named `load_param_{param_name}`
2. A method for …
=> Add Custom Database Parameter Loader

development/nautobot_config.py, docs/admin/integrations/infoblox_setup.md, nautobot_ssot/integrations/infoblox/constant.py, nautobot_ssot/integrations/infoblox/diffsync/adapters/infoblox.py, nautobot_ssot/integrations/infoblox/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/infoblox/diffsync/models/base.py, nautobot_ssot/integrations/infoblox/diffsync/models/nautobot.py, nautobot_ssot/integrations/infoblox/utils/client.py, nautobot_ssot/tests/test_contrib.py, pyproject.toml
- Add a new setting to optionally specify a single Network View to load from Infoblox
- Address the possibility of an extensible attribute containing multiple values
- Add support for Nautobot IP address types
- Move debug message `Creating IP Address {addr}` under a debug check to prevent unintended logging
=> Add single network view and IP Address type support

development/nautobot_config.py, nautobot_ssot/integrations/aristacv/constant.py, nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py, nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/aristacv/diffsync/models/base.py, nautobot_ssot/integrations/aristacv/diffsync/models/cloudvision.py, nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py, nautobot_ssot/integrations/aristacv/jobs.py, nautobot_ssot/integrations/aristacv/signals.py, nautobot_ssot/integrations/aristacv/utils/cloudvision.py, nautobot_ssot/integrations/aristacv/utils/nautobot.py, nautobot_ssot/integrations/device42/signals.py, nautobot_ssot/tests/aristacv/test_cloudvision_adapter.py, nautobot_ssot/tests/aristacv/test_jobs.py, nautobot_ssot/tests/aristacv/test_utils_cloudvision.py, nautobot_ssot/tests/aristacv/test_utils_nautobot.py, nautobot_ssot/tests/device42/unit/test_utils_nautobot.py
This PR includes a variety of fixes for the Arista Cloudvision integration:
- Fixes PLUGINS_CONFIG settings to use `aristacv_` prepending.
- Adds Prefix DiffSync model to track parent prefix for IPAddresses.
- Adds IPAssignment DiffSync model to track IPAddress to Interface mappings.
=> Arista CVP Integration Fixes

nautobot_ssot/jobs/base.py
This PR addresses the issue brought up in #329.
As we now need to allow Exceptions to be thrown to mark a Job as failed we need to remove the try/except block. The rollback also isn't a concern as the atomic transaction wrapper was removed in Nautobot 2.0.
=> Allow Exceptions To Fail Job

nautobot_ssot/integrations/ipfabric/diffsync/diffsync_models.py, nautobot_ssot/integrations/ipfabric/utilities/nbutils.py
Wrap the majority of database calls around a try/except to prevent job failure from individual object failure, and add logging about failures
=> Wrap IPFabric's database calls around try/except

nautobot_ssot/integrations/aci/diffsync/models/nautobot.py
There's a bug in ACI where it's performing a `get_or_create` for LocationType of Site when trying to get a Location but this is wrong as `get_or_create` returns a tuple when we only want the first item from the tuple. As the Site LocationType is created in signals we should be able to just do a get for it.
This also fixes the calls that were using `get_identifiers()` which is unnecessary as that var is on the self variable.
=> Fix ACI LocationType Bug

nautobot_ssot/contrib.py, nautobot_ssot/tests/test_contrib.py
=> implements caching mechanism into the NautobotAdapter

docs/dev/jobs.md, docs/user/modeling.md, nautobot_ssot/contrib.py, nautobot_ssot/tests/test_contrib.py
Supersedes #291 
- Rename `CustomFieldAnnotation.name` to `CustomFieldAnnotation.key`
- Keep around backwards compatibility for using `name`
- Clarify supported types of fields for identifiers
- Add tests for custom fields in identifiers
=> fixes custom field contrib functionality

nautobot_ssot/contrib.py, nautobot_ssot/tests/test_contrib.py
I had an SSoT job break because at least in Python 3.11 `Klass.__annotations__` does not show annotations of parent classes, whereas in 3.8 it does. This PR changes that behaviour to be uniform across all Python versions.
=> use typing.get_type_hints everywhere in favor of __annotations__

nautobot_ssot/contrib.py
Optional has always existed in the typing module, so there is no need to import from typing_extensions, which has only recently added it to the list of importable objects.
=> Import Optional from typing directly

nautobot_ssot/contrib.py, nautobot_ssot/tests/test_contrib.py
This drastically simplifies the method implementation and also makes the PK available for other uses where needed. It also is very cheap, because we load all objects already anyway.
=> change contrib.NautobotModel.get_from_db to use a PK

nautobot_ssot/contrib.py, nautobot_ssot/tests/test_contrib.py
This PR changes `nautobot_ssot.contrib.NautobotModel` such that when an error occurs in `create`, `update` or `delete` it raises the appropriate diffsync exception class so that it can be used properly with the `CONTINUE_ON_FAILURE` global diffsync flag: https://diffsync.readthedocs.io/en/latest/core_engine/index.html#supported-global-flags
Furthermore, error handling was added in a lot of places to make diagnosis of errors easier.
=> improve error handling in contrib

changes/390.changed, nautobot_ssot/contrib/adapter.py
This should provide a more consistent and bug-free experience as we are directly utilizing a standard library API.
=> use typing.get_args in contrib in favor of accessing __args__

changes/407.fixed, docs/admin/install.md, nautobot_ssot/jobs/__init__.py
This should add additional logic which checks if the value of `hide_example_jobs` is_truthy or not
=> App Setting 'hide_example_jobs' is_truthy check

changes/409.fixed, nautobot_ssot/integrations/infoblox/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/infoblox/diffsync/models/nautobot.py, nautobot_ssot/integrations/infoblox/signals.py, nautobot_ssot/integrations/infoblox/utils/diffsync.py, nautobot_ssot/tests/infoblox/test_tags_and_cfs.py
This PR fixes object tagging and custom field updates for Nautobot objects synced to/from Infoblox.
- Adds content types to tags defined by Infoblox SSoT.
- Adds VLAN and VLANGroup to objects being tagged, or having custom field updated.
- Fixes custom field access attribute.
- Removes stale code from `NautobotAdapter` `sync_complete()` method.
- Adds tests checking if tagging and custom field logic is correctly executed.
=> Fix tagging and custom field updates for objects synced to/from Infoblox.

changes/413.fixed, nautobot_ssot/integrations/ipfabric/diffsync/adapter_ipfabric.py, nautobot_ssot/tests/ipfabric/test_ipfabric_adapter.py, nautobot_ssot/tests/test_contrib_adapter.py
Previously these were using `fetch`, which does not collect all results. Switching this to use `all` will get all relevant data points.
=> Fix IPFabric technology calls to us `all`

nautobot_ssot/integrations/servicenow/diffsync/adapter_servicenow.py, nautobot_ssot/integrations/servicenow/diffsync/models.py, nautobot_ssot/integrations/servicenow/jobs.py
Added delete functionality to ServiceNowCRUDMixin in models.py. Disabled cacheing functionality in models.py as it was causing unpredictable results when testing deleting records from ServiceNow. Tested this code with a ServiceNow personal development environment and everything worked as intended in the current format. 
I was unsure as to whether the delete functionality should be available by default in the ServiceNow job but it is currently available by default. Please contact me with any questions/concerns.
=> Ssot snow delete function

changes/414.changed, nautobot_ssot/integrations/ipfabric/diffsync/adapter_ipfabric.py, nautobot_ssot/integrations/ipfabric/utilities/utils.py, nautobot_ssot/tests/ipfabric/test_utils.py
Adds regex matching of interface names for when IPFabric does not provide a media_type.
=> Improve IPFabric matching of InterfaceTypes

docs/admin/release_notes/version_1.6.md, pyproject.toml
- [243](https://github.com/nautobot/nautobot-app-ssot/pull/243) - Fix Infoblox import_subnet for ltm-1.6 by @jdrew82
- [261](https://github.com/nautobot/nautobot-app-ssot/pull/261) - Fix Device42 documentation. by @jdrew82
- [419](https://github.com/nautobot/nautobot-app-ssot/pull/419) - Fix Device42 Plugin Settings for LTM by @jdrew82
- [245](https://github.com/nautobot/nautobot-app-ssot/pull/245) - IPFabric integration settings updates by @alhogan
- [357](https://github.com/nautobot/nautobot-app-ssot/pull/357) - backport contrib changes to LTM by @Kircheneer
- [361](https://github.com/nautobot/nautobot-app-ssot/pull/361) - Backport of #350 by @Kircheneer
- [363](https://github.com/nautobot/nautobot-app-ssot/pull/363) - Backport #362 by @Kircheneer
- …
=> Release v1.6.4

changes/367.added, changes/367.fixed, changes/398.changed, changes/407.fixed, changes/409.fixed, changes/413.fixed, changes/414.changed, changes/418.housekeeping, changes/421.housekeeping, changes/427.housekeeping, docs/admin/release_notes/version_1.6.md, docs/admin/release_notes/version_2.6.md, mkdocs.yml, pyproject.toml
- [#367](https://github.com/nautobot/nautobot-app-ssot/issues/367) - Added support of Roles, Platforms, Manufacturers, DeviceTypes, and Devices to example Jobs.
- [#398](https://github.com/nautobot/nautobot-app-ssot/issues/398) - Changed Arista Cloud Vision jobs to optionally use ExternalIntegration.
- [#414](https://github.com/nautobot/nautobot-app-ssot/issues/414) - Changed IPFabric interface media matching to fall back on interface names.
- [#367](https://github.com/nautobot/nautobot-app-ssot/issues/367) - Fixed issues with example Jobs.
- [#407](https://github.com/nautobot/nautobot-app-ssot/issues/407) - + Fixed logic check for 'hide_example_jobs' when defined, and also set to False.
- [#409](https://github.com/nautobot/nautobot-app-ssot/issues/409) - + Fixes tagging and custom field …
=> Release v2.6.0

changes/437.changed, nautobot_ssot/integrations/infoblox/utils/client.py
Changed the Infoblox `utils.client` to make API calls using `requests.Session` instead of `requests.request`.
This change should result in 1.5 - 3x performance improvement when loading data from Infoblox.
=> [Infoblox] Replace `requests.request` with `requests.Session` in the Infoblox API client.

changes/463.fixed, nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py
This addresses closes issue #463 to have `import_active` config setting passed to get_devices() call.
=> Correct CVP Integration Call to get_devices()

changes/497.housekeeping, nautobot_ssot/tests/ipfabric/test_nbutils.py
Correct the mocks in `test_nbutils.py` so that tests pass with Nautobot 2.3.0 prerelease.
=> Fix #497 - compatibility with Nautobot 2.3.

changes/488.fixed, docs/admin/integrations/infoblox_setup.md
The [markdown tables](https://docs.nautobot.com/projects/ssot/en/latest/admin/integrations/infoblox_setup/#prerequisites) don't currently render properly in the docs.
=> Fix markdown tables in Infoblox setup docs

changes/526.changed, nautobot_ssot/jobs/base.py, nautobot_ssot/jobs/examples.py
This changes the `NautobotRemote` adapter to use a generator to process large lists of data instead of building a large list and returning it.
This also updates the logging output to be more human-readable.
Also confirmed with `docker stats` that the container memory utilization only increased by ~110MiB after running the job
=> Update the ExampleDataSource job to improve memory utilization

changes/521.fixed, nautobot_ssot/jobs/examples.py
This PR is to close out #521. It replaces the generalized Exceptions with SecretError and raises a custom Exception if SecretsGroup isn't found on ExternalIntegration.
=> Fix Generalized Exceptions in Example Jobs

.github/workflows/ci.yml, development/docker-compose.mysql.yml, tasks.py
This fixes the `invoke check-migrations` command so that upstream testing doesn't fail on this step anymore.
=> fixed invoke check-migrations in ltm

changes/530.fixed, nautobot_ssot/integrations/infoblox/models.py
Also closes #530 for 2.8 release train
=> Disable saved view for SSOTInfobloxConfig on LTM-2.8

changes/561.fixed, nautobot_ssot/integrations/ipfabric/diffsync/adapter_ipfabric.py
Fixes: https://github.com/nautobot/nautobot-app-ssot/issues/561
Set `strict=False` for parsing IP Networks using `ipaddress.ip_network`
=> IP Fabric Bug - Network has host bits set

changes/571.fixed, nautobot_ssot/integrations/aristacv/utils/cloudvision.py
This PR closes #571 and ensures that the URL scheme is included in the POST call to establish the CVP client.
=> Ensure URL Scheme in POST

changes/582.fixed, nautobot_ssot/jobs/base.py
Stumbled upon a print statement that needs to be removed.
=> Removing erroneous print statement

changes/467.fixed, nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py, nautobot_ssot/integrations/aristacv/utils/cloudvision.py, nautobot_ssot/tests/aristacv/test_utils_cloudvision.py
This should close out #467. This simply puts a try/except in get_tags_by_type() to handle possible RpcError's being thrown.
=> Handle RpcError in CVP

changes/590.changed, nautobot_ssot/contrib/model.py
Without this the actual error message is swallowed, making it very hard to debug validation errors.
=> improves error message for contrib validated save

changes/310.added, docs/user/modeling.md, nautobot_ssot/contrib/typeddicts.py, nautobot_ssot/integrations/bootstrap/diffsync/adapters/bootstrap.py, nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py
Add common TypedDicts for use with many-to-many and one-to-many relationships.
=> Add common TypedDicts used for M2M

.github/CODEOWNERS, changes/593.added, changes/593.fixed, changes/593.housekeeping, nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py, nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py, nautobot_ssot/integrations/dna_center/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/meraki/diffsync/adapters/meraki.py, nautobot_ssot/integrations/meraki/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/meraki/diffsync/models/base.py, nautobot_ssot/integrations/meraki/diffsync/models/meraki.py, nautobot_ssot/integrations/meraki/diffsync/models/nautobot.py, nautobot_ssot/tests/dna_center/test_adapters_dna_center.py, nautobot_ssot/tests/meraki/test_models_nautobot.py
- Fixes bug where multiple locations assigned to a Prefix would cause Meraki integration to fail.
- Added ability to Meraki and DNA Center integrations to allow renaming of imported locations using `name` key in location map option.
- Fixed DNA Center loading incorrect names for buildings and floors in Nautobot adapter.
- Added missing code owners for DNA Center, Meraki, and Itential integrations.
- Fixed KeyError being thrown when port is missing from uplink_settings dict in Meraki integration.
- Fixed bug in Bootstrap integration that occurs when loading ValidatedSoftware in a system where SoftwareLCM doesn't exist.
=> Various Bugfixes

changes/411.fixed, nautobot_ssot/migrations/0007_replace_dashed_custom_fields.py
This PR closes #411 and fixes the imports in the migration that are causing the installation bug discussed in 411.
=> Fix CustomField Migration

changes/449.added, changes/449.fixed, nautobot_ssot/integrations/servicenow/diffsync/adapter_nautobot.py, nautobot_ssot/integrations/servicenow/diffsync/adapter_servicenow.py, nautobot_ssot/integrations/servicenow/jobs.py
SSoT ServiceNow fixed and updates for Nautobot 2.0
Addresses #449
=> SSoT ServiceNow fixes and updates for Nautobot 2.0

.github/CODEOWNERS, README.md, changes/605.documentation, changes/605.housekeeping
I noticed that our documentation had missed some acknowledgements for integrations and also the code owner for the Citrix integration.
=> Add Missing Acknowledgements and Code Owner

changes/607.fixed, changes/607.housekeeping, nautobot_ssot/integrations/citrix_adm/jobs.py, nautobot_ssot/integrations/meraki/diffsync/adapters/meraki.py, nautobot_ssot/integrations/meraki/utils/meraki.py
This PR fixes the hostname_mapping functionality in the Citrix ADM integration. I found when used in client that I had used JSONVar when I meant a StringVar as it's a list of tuples. This also does a bit of housekeeping to remove a duplicate `parse_hostname_for_role()` that I had missed in the Meraki integration.
=> Fix hostname_mapping in Citrix ADM

changes/610.fixed, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
This PR closes the bug discovered in #610.
=> Fix delete function for NautobotValidatedSoftware

changes/612.fixed, nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py
Fixed loading platforms with no Manufacturer assigned in the Nautobot Adapter causing an AttributeError.
- [ X ] Explanation of Change(s)
- [ X ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ X ] Attached Screenshots, Payload Example
- [ X ] Unit, Integration Tests
- [ X ] Documentation Updates (when adding/changing features)
- [ X ] Outline Remaining Work, Constraints from Design
=> fix: 🐛 fix issue #612 loading platforms with no manufacturer

changes/616.fixed, nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py
This closes #616 and fixes the issue where a Device with None for SoftwareType is loaded.
=> Ensure that Devices without a Platform are not loaded.

changes/614.fixed, nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/bootstrap/diffsync/models/base.py, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py, nautobot_ssot/integrations/bootstrap/fixtures/global_settings.yml, nautobot_ssot/tests/bootstrap/fixtures/global_settings.json, nautobot_ssot/tests/bootstrap/test_setup.py
Fix Pydantic errors
Allow creation of platforms with no manufacturer assigned.
Fix improper normalization on time_zone attribute on Location objects.
=> fix: 🐛 Pydantic errors and field normalization issues

changes/634.fixed, nautobot_ssot/integrations/servicenow/diffsync/adapter_nautobot.py
When running the Nautobot ⟹ ServiceNow job with a site filter set, you expect the job to sync only the specified locations to ServiceNow. 
However, it appears that the job currently loads only the parent locations, not the specified location itself.
This is fixed by initializing the locations list with the user-selected location and then loading the parent locations of that selection.
=> Service Now Integration - Fixes issue #634

.github/workflows/ci.yml, changes/641.fixed, nautobot_ssot/integrations/bootstrap/diffsync/models/bootstrap.py, nautobot_ssot/tests/infoblox/test_tags_and_cfs.py
Fixes: #641 
Fix incorrectly nested classes for IPAM models in the bootstrap models.
=> Bootstrap: fix imports for ipam models

changes/646.fixed, nautobot_ssot/integrations/citrix_adm/diffsync/adapters/citrix_adm.py, nautobot_ssot/integrations/citrix_adm/diffsync/models/nautobot.py
Closes #646 and addresses the bug in Citrix ADM where the wrong parent Prefix is chosen for an IPAddress and Nautobot won't import the IPAddress.
=> Fix Wrong Parent Prefix in Citrix ADM

changes/648.fixed, nautobot_ssot/integrations/citrix_adm/diffsync/models/nautobot.py, nautobot_ssot/integrations/meraki/diffsync/models/nautobot.py, tasks.py
This PR closes #648 and fixes the issue with deleting a SoftwareVersion that is used with a ValidatedSoftware. I found that this same issue was also possible with Meraki integration so replicated the check there.
=> Fix Citrix ADM Removing Used SoftwareVersions

changes/650.fixed, nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py
Corrected the names of Floors used in loading Devices to match format when Floors are loaded. This fixes the issue where Devices were being assigned to the wrong Floors by mistake.
=> Fix Device Floor Name to Match Loaded

changes/597.fixed, nautobot_ssot/integrations/aci/diffsync/models/nautobot.py
Fixes the ACI integration CRUD operations use of Site LocationType when it should be using whichever LocationType is specified for the Job's device_site Location or APIC Location.
=> Correct ACI LocationType To Match Job Settings

changes/654.fixed, nautobot_ssot/integrations/aci/signals.py
Avoid duplicate key exception on startup by only passing tag name during tag enforcement.
Ensure tag content_types and color are properly configured.
=> Preserve ACI Tag color and device types settings

changes/680.fixed, nautobot_ssot/integrations/meraki/diffsync/adapters/nautobot.py
This should fix the error that was described in #680 where there were multiple Locations with the same name.
=> Fix Duplicate Location Error in Meraki

changes/686.changed, nautobot_ssot/integrations/solarwinds/utils/solarwinds.py, nautobot_ssot/tests/solarwinds/test_utils_solarwinds.py
Solarwinds & SNMP for some reason pulls the information needed for DeviceType into the Solarwinds IOSImage field. This PR simiply changes the SolarWinds integration to use this field specifically for Aruba devices.
=> Use IOSImage field to grab Aruba DeviceType

changes/632.added, docs/user/integrations/dna_center.md, nautobot_ssot/integrations/dna_center/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/dna_center/diffsync/models/base.py, nautobot_ssot/integrations/dna_center/diffsync/models/nautobot.py, nautobot_ssot/integrations/dna_center/signals.py, nautobot_ssot/integrations/dna_center/utils/nautobot.py, nautobot_ssot/tests/dna_center/test_models_nautobot.py
This PR adds support for the [Object Metadata](https://docs.nautobot.com/projects/core/en/stable/user-guide/platform-functionality/objectmetadata/) feature that was added in Nautobot 2.3 to the DNA Center integration. The following additions have been made:
- Add the same functionality to the remaining integrations.
- Will need to add unit tests to cover this once we have CI using 2.3+.
- [] Unit, Integration Tests
=> Add Metadata to DNA Center Integration

changes/703.fixed, nautobot_ssot/contrib/model.py
Had this in an environment where the MTU for an interface was empty, it didn't raise a validation error but rather a value error.
=> adds catching of ValueError on validated_save in contrib

changes/729.fixed, nautobot_ssot/integrations/infoblox/diffsync/models/nautobot.py
The location of a prefix should be synced from the “site” or “location” extensibility attribute of an Infoblox network.
After reviewing the code, I identified that we were setting [location_id ](https://github.com/michalis1/nautobot-app-ssot/blob/6bf86de74e7d6248cdaf9571aa62c960ef679d19/nautobot_ssot/integrations/infoblox/diffsync/models/nautobot.py#L50) instead of the location of a prefix.
=> Fix the synchronization of the prefix location from Infoblox extensibility attributes. (#729)

changes/731.changed, nautobot_ssot/integrations/solarwinds/diffsync/adapters/solarwinds.py, nautobot_ssot/tests/solarwinds/test_solarwinds_adapter.py
Allows better differentiation between Aruba OS types, as well as add support for (EOL) 8500-WLC AireOS platform type.
Used fantastic chart created here to help with model types: https://github.com/networktocode/netutils/pull/588#issuecomment-2672972706
=> Update Aruba/Cisco Platform logic

changes/740.fixed, nautobot_ssot/migrations/0013_update_solarwinds_customfields.py
This PR adds a new migration to update any System of Record CustomFields that were using Solarwinds to now be SolarWinds. This is to address the update that was done in #696 where the Nautobot adapter load is now expecting SolarWinds to be in the CustomField.
=> Add Migration for SoR CustomField

changes/745.added, docs/user/integrations/bootstrap.md, nautobot_ssot/integrations/bootstrap/diffsync/adapters/bootstrap.py, nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/bootstrap/diffsync/models/base.py, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
Added `enabled` parameter for scheduled_jobs, in Boostrap integration.
I noticed that disabled Scheduled Jobs do not appear in the list view in the UI, due to [this](https://github.com/nautobot/nautobot/blob/cb9bacbed04e7b8849cd24bd28094b632e093ca2/nautobot/extras/views.py#L1956) in Nautobot core. I'd love to see if that can be changed, but in the meantime I also added a warning to the docs for anyone using this parameter.
=> Bootstrap integration: add enabled option for scheduled_jobs

changes/744.added, nautobot_ssot/integrations/solarwinds/utils/solarwinds.py, nautobot_ssot/tests/solarwinds/test_utils_solarwinds.py
Cisco 8540 WLC's were getting `WS-` prepended to their device_type, causing them to be incorrectly categorized as ios, not aireos. This resolves that issue.
Adding the one extra 'if' check caused Pylint to complain with `R0916: Too many boolean expressions in if statement`, so I refactored that logic a tad as well.
Added one extra test case for the `standardize_device_type` function for this case.
=> SolarWinds integration: Add 'wireless' to device_type checks

.github/workflows/ci.yml, changes/762.dependencies, poetry.lock, pyproject.toml
This PR drops support for Python 3.8 to match core Nautobot 2.4.6 and re-enable compatibility.
=> Drop Python 3.8 Support

changes/750.fixed, nautobot_ssot/integrations/servicenow/utils.py, nautobot_ssot/tests/servicenow/test_jobs.py
Updated the ServiceNow integration config loading to allow instance from the DB config. Previously it was being overridden by the default app settings in __init__.py
Tests were also updated to make sure this is captured the same way in the future.
=> Updated ServiceNow instance config loading

changes/772.fixed, docs/admin/integrations/infoblox_setup.md, nautobot_ssot/integrations/infoblox/models.py
The default value for the **Network Views to Nautobot Namespace** setting in the Infoblox integration should be a dictionary, not a list. 
Current (incorrect) default:
```json
[
{
"default": "Global"
}
]
```
Correct default:
```json
{
"default": "Global"
}
```
=> Infoblox Integration - The default value for the Network Views to Nautobot Namespace setting should be a dictionary (#772)

changes/760.fixed, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
Incorrect keyword `name` was being used for User object, the correct keyword is `username`.
=> Fixes #760, bootstrap scheduled_job User update

changes/793.fixed, nautobot_ssot/integrations/citrix_adm/diffsync/models/nautobot.py, nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py
This PR resolves the issue described in #793 where multiple Prefixes were returned when finding the parent for an IPAddress in the Citrix ADM integration. I've also found another bug in the DNA Center integration where I missed checking for a parent Location on the DNAC Controller Location hierarchy.
=> Fix Prefix MultipleObjectsReturned Error in Citrix ADM Integration

changes/796.fixed, nautobot_ssot/integrations/aristacv/utils/cloudvision.py
This PR is intended to fix the issue where the wrong URL is being passed to the CVP client during the version check.
Need to validate this fixes the issue with a CVP instance.
=> Fix AuthFailure During Version Check in CVP Integration

changes/802.fixed, nautobot_ssot/contrib/sorting.py
Closes: #802
Removed `issubclass` check referencing invalid class object on affected line.
=> Fix contrib sorting TypeError

changes/816.fixed, nautobot_ssot/contrib/sorting.py, nautobot_ssot/tests/contrib/test_sorting.py
=> Fix sorting __annotation__ `AttributeError` in sorting

changes/819.fixed, nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py
Bugfix for attempting to load ValidatedSoftware models if DLM app isn't installed. 
- [ X ] Explanation of Change(s)
- [ X ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ X ] Attached Screenshots, Payload Example
- [ X ] Unit, Integration Tests
- [ X ] Documentation Updates (when adding/changing features)
- [ X ] Outline Remaining Work, Constraints from Design
=> Fix Check for DLM Installed Before Loading ValidatedSoftware

changes/784.fixed, nautobot_ssot/contrib/adapter.py
We have _handle_to_many_relationship method that is defined as a staticmethod. However, it uses _handle_typed_dict directly from its own class NautobotAdapter.
Therefore, an adapter would inherit NautobotAdapter cannot overwrite this method because it would still be the one from its parent that is called.
=> Overwrite _handle_typed_dict

changes/836.added, nautobot_ssot/models.py
Added `hide_in_diff_view` flag to the `Sync` and `SyncLogEntry` to hide those models by default in version control diff view.
=> Hide `Sync` and `SyncLogEntry` in version control diff view.

changes/842.fixed, nautobot_ssot/integrations/meraki/diffsync/adapters/meraki.py, nautobot_ssot/tests/meraki/fixtures/get_org_uplink_addresses_by_device.json, nautobot_ssot/tests/meraki/test_adapters_meraki.py
This PR fixes the bug described in #842 where an IPv6 address is passed to a function with an IPv4 prefix throwing a TypeError. This should now allow for IPv6 addresses seen on the uplinks.
=> Fix Meraki Loading Invalid IP Version

changes/845.fixed, nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py, nautobot_ssot/integrations/dna_center/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/dna_center/diffsync/models/base.py, nautobot_ssot/tests/dna_center/test_adapters_dna_center.py, nautobot_ssot/tests/dna_center/test_models_nautobot.py
This PR fixes a bug where Meraki devices were added to the failed device list even when the `import_meraki` setting is False.
N/A
=> Fix DNA Center Loading Meraki

changes/867.fixed, docs/admin/integrations/servicenow_setup.md, nautobot_ssot/integrations/servicenow/diffsync/adapter_servicenow.py, nautobot_ssot/tests/servicenow/test_adapter_servicenow.py
* Passes through the `table_query` attribute from the servicenow `mappings.yaml`. This is called out in the comments - `Only load companies that are flagged as manufacturer: true, as those correspond to Nautobot Manufacturer records` but in implementation this value was not being referenced anywhere so it was a noOp. I repaired the connection and tested locally to see that it properly only brings in company names that are listed as manufacturers.
* Added file output to give user an indication of all duplicates encountered in each servicenow table.
* Behavior is now to swallow, log overview of how many duplicates encountered, and provide file output outlining what duplicates were encountered.
=> SNOW - Gracefully handle duplicates, repair table_query feature

changes/880.changed, nautobot_ssot/integrations/bootstrap/diffsync/adapters/bootstrap.py, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
When adding ValidatedSoftware, if the software version specified is missing, it will automatically add the software as well.
=> bootstrap integration: validatedSW, auto-add missing SW

changes/904.fixed, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
Adds a Warning log message that Validated Software is unable to find the SoftwareVersion it points to thus unable to be created, and handles the Exceptions so the Job can continue to run.
=> fix: bootstrap validated_software missing version

changes/881.fixed, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
All related only to Bootstrap integration:
- Fixes early return when creating SecretsGroups
- Fixes exception occurring if Secret within a SecretGroup getting created does not actually exist within Nautobot.
- Fixes issue with incorrect SecretsGroupAssociation field being used.
Since Secrets are not required in order to create a SecretGroup, and looking at the original error and assuming intent from that, I believe it's OK to still create the Secret Group just without the missing Secret, but logging as warning to ensure the end-user is able to notice this issue.
=> fix: bootstrap missing Secret in SecretsGroup

changes/596.fixed, nautobot_ssot/integrations/infoblox/diffsync/adapters/infoblox.py
Handle HTTP 404 exception case for expired A record and PTR reference, instead of the failing our job we log the event as a warning.
=> Handle HTTP 404 exception case for expired an A record and PTR reference

changes/926.fixed, nautobot_ssot/contrib/model.py
When using contrib models without the contrib adapter, the `metadata_type` attribute is missing from the adapter instance during model [creation](https://github.com/nautobot/nautobot-app-ssot/blob/a20baa131ab1c30d51d24f8cc8ea43fc92cf3e2b/nautobot_ssot/contrib/model.py#L113) or [update](https://github.com/nautobot/nautobot-app-ssot/blob/a20baa131ab1c30d51d24f8cc8ea43fc92cf3e2b/nautobot_ssot/contrib/model.py#L79). To fix this, I first check whether the `metadata_type` attribute exists on the adapter instance, and then evaluate its value if present.
=> Fix issue with metadata_type when contrib models are used without the contrib adapter.

changes/723.fixed, nautobot_ssot/contrib/adapter.py, nautobot_ssot/contrib/model.py, nautobot_ssot/tests/test_contrib_adapter.py
Adjusted _handle_single_parameter to correctly implement the intent from the `CustomFieldAnnotation` docstring:
```
Note that for backwards compatibility purposes it is also possible to use `CustomFieldAnnotation.name` instead of
`CustomFieldAnnotation.key`.
```
=> Fix _handle_single_parameter metadata `key` vs `name` inconsistency

changes/940.fixed, nautobot_ssot/integrations/citrix_adm/diffsync/adapters/citrix_adm.py, nautobot_ssot/integrations/citrix_adm/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/citrix_adm/diffsync/models/base.py, nautobot_ssot/integrations/citrix_adm/diffsync/models/nautobot.py, nautobot_ssot/tests/citrix_adm/test_adapters_citrix_adm.py, nautobot_ssot/tests/citrix_adm/test_adapters_nautobot.py, nautobot_ssot/tests/citrix_adm/test_models_nautobot.py
This PR fixes the issue in the Citrix ADM integration where an error is thrown when creating an IPAddressToInterface object.
N/A
=> Fix Citrix ADM Throwing IP Error

changes/964.fixed, nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py, nautobot_ssot/integrations/aristacv/diffsync/adapters/nautobot.py, nautobot_ssot/integrations/aristacv/utils/cloudvision.py
- Fixes behavior when syncing a EVPN fabric. Duplicate IPAddresses are usual in such setup, this changes support such use case.
- Implements TAG deduplication.
- Removes log noise when duplicate IP or IP assignments are found - visible in debug mode only.
- Fixes cert failures for CVaaS implementations (verify cert = False). Such cases can happen when SSL inspection for nautobot workers is in place.
- Gets rid of device vrf tags, which lead to inconsistent syncs.
=> [CLOUDVISION SSOT] Sync job Fails when same IP address assigned to multiple interfaces in same Namespace #964 

changes/980.fixed, nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
Adds the check for DLM vs Nautobot support for SoftwareVersions to the delete() method, as is already in use in the create() and update() methods.
=> Fix Bootstrap Software deletion error.
