- docs/changelog.md
- pyproject.toml
> Add post-1.0.1 changes to changelog, bump development version to 1.1.0b1

- .github/CODEOWNERS
@glennmatthews if you want me to help you reviewing PRs on this repo feel free to accept me as codeowner (so I receive the requests for review)
> Add chadell to codeowners

- nautobot_ssot/jobs/base.py
...to be created, updated, deleted or not changed
> Add INFO log message about the number of elements 

- nautobot_ssot/jobs/base.py
- nautobot_ssot/tests/test_jobs.py
Addresses issue #47
TODO:
- add a test case to catch this issues
> Use self.diff instead of self.sync.diff

- .github/workflows/ci.yml
@ubajze could you add the `secrets.SLACK_WEBHOOK_URL` to this repository?
> Add slack notify CI step for release

- .github/workflows/upstream.yml
- .github/workflows/upstream_testing.yml
- README.md
- development/Dockerfile
- docs/index.md
- nautobot_ssot/__init__.py
- pyproject.toml
- Updated Dockerfile to be compatible with upstream testing
- Added workflow fragment to trigger testing
> Enable Upstream Testing

- nautobot_ssot/__init__.py
Updating to better inform user of what the app is/does...changes will be reflected in "Installed Plugins" in the UI.
> Update __init__.py to better describe the app in the UI

- pyproject.toml
> Fix packaging version in pyproject.toml.

- .bandit.yml
- docs/admin/release_notes/version_1.3.md
- mkdocs.yml
- nautobot_ssot/migrations/0001_initial.py
- nautobot_ssot/migrations/0002_performance_metrics.py
- nautobot_ssot/migrations/0003_alter_synclogentry_textfields.py
- nautobot_ssot/migrations/0004_sync_summary.py
- poetry.lock
- pyproject.toml
> Release v1.3.1

- docs/admin/compatibility_matrix.md
- docs/admin/release_notes/version_2.0.md
- mkdocs.yml
- nautobot_ssot/tests/test_basic.py
- pyproject.toml
This PR is to prepare for cutting release for v2.0.0-beta2. 
- Updated version to specify beta2 to match Nautobot.
- Added release notes to summarize changes.
> Release v2.0.0b2

- docs/admin/compatibility_matrix.md
- docs/admin/release_notes/version_2.0.md
- pyproject.toml
This PR is to get ready for the 2.0.0rc1 release.
> Release v2.0.0rc1

- docs/admin/release_notes/version_2.0.md
- pyproject.toml
This PR is to prepare next-2.0 branch for cutting a release to support RC2.
> Release v2.0.0rc2

- docs/admin/compatibility_matrix.md
- docs/admin/release_notes/version_1.4.md
- docs/admin/release_notes/version_1.5.md
- mkdocs.yml
- pyproject.toml
This PR is to make the required changes for v1.5.0.
> Release v1.5.0

- .github/workflows/ci.yml
> Attempt fixing CI error in #214

- nautobot_ssot/__init__.py
Added link to the error message notifying about conflicting apps.
> Add conflicting message link

- .github/CODEOWNERS
This PR is for adding the various code owners for the integrations.
> Add CODEOWNERS for the various integrations

- .github/CODEOWNERS
> Add plugin-ssot as integration code owners

- docs/admin/install.md
- docs/admin/integrations/index.md
- docs/admin/upgrade.md
- docs/user/app_overview.md
- docs/user/integrations/device42.md
- docs/user/integrations/index.md
This PR is to fix the documentation for Device42 in the LTM branch. I've also added @Kircheneer as a maintainer.
> Fix Device42 documentation.

- docs/admin/install.md
- docs/admin/integrations/index.md
- docs/admin/upgrade.md
- docs/user/app_overview.md
- docs/user/integrations/device42.md
- docs/user/integrations/index.md
This PR is for adding Device42 and links to the various integration lists that were missed. I've also added @Kircheneer as a maintainer to the documentation.
> Fix Documentation for Device42

- docs/user/integrations/ipfabric.md
- nautobot_ssot/integrations/device42/utils/nautobot.py
- nautobot_ssot/integrations/infoblox/diffsync/adapters/nautobot.py
- nautobot_ssot/integrations/infoblox/signals.py
- nautobot_ssot/integrations/infoblox/utils/diffsync.py
- nautobot_ssot/integrations/ipfabric/constants.py
- nautobot_ssot/integrations/ipfabric/diffsync/adapter_nautobot.py
- nautobot_ssot/integrations/ipfabric/diffsync/diffsync_models.py
- nautobot_ssot/integrations/ipfabric/jobs.py
- nautobot_ssot/integrations/ipfabric/signals.py
- nautobot_ssot/integrations/ipfabric/utilities/nbutils.py
- nautobot_ssot/integrations/servicenow/diffsync/adapter_nautobot.py
- nautobot_ssot/integrations/servicenow/signals.py
- nautobot_ssot/migrations/0007_remove_dashed_custom_fields.py
- nautobot_ssot/migrations/0007_replace_dashed_custom_fields.py
- nautobot_ssot/tests/device42/unit/test_utils_nautobot.py
This PR is to fix the bug detailed in #274. I believe this is around CustomFields that have dashes in the key when it should be underscores instead. There is a migration included to update any user that might have the old CustomFields and migrate them to the new ones.
> Fix CustomField Bug

- nautobot_ssot/integrations/aristacv/utils/nautobot.py
This should ensure that these objects can be used with Device object and address the bug discussed in #266.
> Ensure Device ContentType on Site LocationType, Role, and Tags in CVP

- docs/dev/debugging.md
- mkdocs.yml
> Adds a debugging guide for SSoT jobs

- .github/workflows/ci.yml
- nautobot_ssot/tests/test_contrib.py
- poetry.lock
- pyproject.toml
- tasks.py
Blocked until merge of https://github.com/nautobot/nautobot/pull/4894
> adds back in all the skipped contrib test cases

- nautobot_ssot/integrations/infoblox/constant.py
- nautobot_ssot/integrations/ipfabric/diffsync/diffsync_models.py
This PR should fix the issue detailed in #323. While I was fixing that the tests also turned up some issues with IPFabric integration that I've fixed.
> Fix Infoblox Config Bug

- nautobot_ssot/contrib.py
- nautobot_ssot/tests/test_contrib.py
use typing.get_type_hints everywhere in favor of __annotations__
> Backport #362

- docs/admin/release_notes/version_1.6.md
- pyproject.toml
- [243](https://github.com/nautobot/nautobot-app-ssot/pull/243) - Fix Infoblox import_subnet for ltm-1.6 by @jdrew82
- [261](https://github.com/nautobot/nautobot-app-ssot/pull/261) - Fix Device42 documentation. by @jdrew82
- [245](https://github.com/nautobot/nautobot-app-ssot/pull/245) - IPFabric integration settings updates by @alhogan
- [357](https://github.com/nautobot/nautobot-app-ssot/pull/357) - Backport contrib changes to LTM by @Kircheneer
- [361](https://github.com/nautobot/nautobot-app-ssot/pull/361) - Backport of #350 by @Kircheneer
- [363](https://github.com/nautobot/nautobot-app-ssot/pull/363) - Backport #362 by @Kircheneer
> Release v1.6.1

- nautobot_ssot/contrib.py
- nautobot_ssot/tests/test_contrib.py
> change contrib.NautobotModel.get_from_db to use a PK

- changes/359.added
- docs/dev/jobs.md
> Add warning for Device Types with Interfaces

- changes/377.fixed
- nautobot_ssot/contrib/adapter.py
- nautobot_ssot/tests/test_contrib_adapter.py
> Allow foreign keys inside of many to many relationships.

- changes/393.fixed
- nautobot_ssot/contrib/adapter.py
- nautobot_ssot/contrib/model.py
- nautobot_ssot/tests/contrib_base_classes.py
- nautobot_ssot/tests/test_contrib_adapter.py
- nautobot_ssot/tests/test_contrib_model.py
> fix: handle custom 1-to-many relationships

- changes/367.added
- changes/367.fixed
- nautobot_ssot/jobs/examples.py
This PR addresses the issues in #367 and updates the example Jobs to support handling Roles, Platforms, Manufacturers, DeviceTypes, and Devices.
> Fix example jobs

- nautobot_ssot/integrations/device42/diffsync/adapters/device42.py
- nautobot_ssot/integrations/device42/diffsync/adapters/nautobot.py
- nautobot_ssot/integrations/device42/diffsync/models/nautobot/assets.py
- nautobot_ssot/integrations/device42/diffsync/models/nautobot/circuits.py
- nautobot_ssot/integrations/device42/diffsync/models/nautobot/dcim.py
- nautobot_ssot/integrations/device42/diffsync/models/nautobot/ipam.py
- nautobot_ssot/tests/device42/unit/test_device42_adapter.py
This PR is to fix all of the plugin settings for the Device42 integration to use the corrected key that includes the required `device42_` prepend.
> Fix Device42 Plugin Settings for LTM

- changes/431.fixed
- nautobot_ssot/integrations/ipfabric/diffsync/adapter_ipfabric.py
Modified note on IPFabricDiffSync from Nautobot to IPFabric as I believe IPFabric is correct.
> Modified note on IPFabricDiffSync from Nautobot to IPFabric

- changes/443.fixed
- development/docker-compose.mysql.yml
- nautobot_ssot/integrations/infoblox/diffsync/adapters/infoblox.py
- nautobot_ssot/integrations/infoblox/utils/client.py
This PR is to address the bug mentioned in #443. It also addresses the logging issue in #177.
> Fix Duplicate IPAddress Loading in Infoblox

- changes/456.fixed
- nautobot_ssot/tests/device42/unit/test_utils_device42.py
This PR is to fix the issue discussed in #455.
> Fix CI for Device42 Test

- nautobot_ssot/tests/device42/unit/test_utils_device42.py
This PR closes #489 and fixes the failing test.
> Fix Upstream Monitor CI

- changes/516.dependencies
- docs/requirements.txt
- poetry.lock
- pyproject.toml
This PR should fix the dependencies for mkdocstrings required for the mkdocs RTD build.
> Fix RTD for 3.0.0

- changes/518.documentation
- docs/dev/upgrade.md
> Minor doc updates on upgrade to 3.0.

- changes/507.fixed
- nautobot_ssot/jobs/examples.py
This PR closes out the issue in #507.
> Fix DataTarget Example Job

- changes/520.added
- docs/admin/integrations/infoblox_setup.md
Documentation updated, Closes issue #520
> Add instructions to enable Infoblox integration

- changes/530.fixed
- nautobot_ssot/integrations/infoblox/models.py
> Disable saved view for SSOTInfobloxConfig 

- changes/479.fixed
- nautobot_ssot/integrations/aci/diffsync/adapters/aci.py
Fixes the bug discovered in #479.
> Fix ACI Bug

- changes/548.fixed
- development/app_config_schema.py
- development/nautobot_config.py
- nautobot_ssot/jobs/base.py
- nautobot_ssot/tests/test_basic.py
- nautobot_ssot/tests/test_jobs.py
- tasks.py
This changes the variable looked at for dryrun to be `self.sync.dry_run` instead of `self.dryrun`.
I can pull out the format changes if need be.
> Update variable used in Dryrun job decision

- changes/558.fixed
- nautobot_ssot/integrations/aci/diffsync/models/nautobot.py
This PR closes issue mentioned in #558.
> Fix VRF Attribute in ACI Prefix.create()

- changes/569.documentation
- docs/admin/install.md
> Add Missing Links in Documentation

- changes/590.changed
- changes/590.fixed
- docs/admin/release_notes/version_1.5.md
- nautobot_ssot/contrib/model.py
improves error message for contrib validated save
> [LTM] Improved contrib error messaging (backport #590)

- changes/621.fixed
- docs/user/integrations/bootstrap.md
- nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
Fixed ASN updates on location objects due to bad key reference. 
- [ X ] Explanation of Change(s)
- [ X ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
> fix: 🐛 fix ASN update on location objects

- changes/624.fixed
- nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py
This PR closes out #624 and fixes the issue where floors weren't being loaded as the building with updated names from Location Map weren't being found.
> Correct Floors Being Loaded in DNAC When Location Map Used

- changes/626.fixed
- nautobot_ssot/integrations/dna_center/diffsync/adapters/nautobot.py
- nautobot_ssot/integrations/dna_center/diffsync/models/nautobot.py
- nautobot_ssot/integrations/dna_center/utils/nautobot.py
- nautobot_ssot/tests/dna_center/test_models_nautobot.py
This PR closes #626 and fixes the issue with SoftwareVersion being updated on a Device.
> Fix SoftwareVersion assignment during Device update.

- changes/692.changed
- nautobot_ssot/migrations/0007_replace_dashed_custom_fields.py
Replacing [model.objects.all()](https://github.com/michalis1/nautobot-app-ssot/blob/1f8c74d25d2cd97043680997ac27b4a328b82554/nautobot_ssot/migrations/0007_replace_dashed_custom_fields.py#L36) with model.objects.iterator().
Indent [cf_list.append(instance)](https://github.com/michalis1/nautobot-app-ssot/blob/1f8c74d25d2cd97043680997ac27b4a328b82554/nautobot_ssot/migrations/0007_replace_dashed_custom_fields.py#L41C13-L41C37) to ensure only modified instances are updated.
> Improve the replace_dashed_custom_fields migration (Issue #692)

- changes/697.fixed
- nautobot_ssot/integrations/aci/signals.py
ACI integration: Change _tag.validated_save() to _tag.save()
> ACI integration: Change _tag.validated_save() to _tag.save()

- README.md
- changes/696.documentation
- docs/admin/release_notes/version_3.4.md
- docs/user/integrations/solarwinds.md
- nautobot_ssot/integrations/solarwinds/__init__.py
- nautobot_ssot/integrations/solarwinds/constants.py
- nautobot_ssot/integrations/solarwinds/diffsync/__init__.py
- nautobot_ssot/integrations/solarwinds/diffsync/adapters/__init__.py
- nautobot_ssot/integrations/solarwinds/diffsync/adapters/nautobot.py
- nautobot_ssot/integrations/solarwinds/diffsync/adapters/solarwinds.py
- nautobot_ssot/integrations/solarwinds/diffsync/models/__init__.py
- nautobot_ssot/integrations/solarwinds/diffsync/models/base.py
- nautobot_ssot/integrations/solarwinds/diffsync/models/nautobot.py
- nautobot_ssot/integrations/solarwinds/diffsync/models/solarwinds.py
- nautobot_ssot/integrations/solarwinds/jobs.py
- nautobot_ssot/integrations/solarwinds/signals.py
- nautobot_ssot/integrations/solarwinds/utils/__init__.py
- nautobot_ssot/integrations/solarwinds/utils/solarwinds.py
- nautobot_ssot/tests/solarwinds/__init__.py
- nautobot_ssot/tests/solarwinds/conftest.py
- nautobot_ssot/tests/solarwinds/test_jobs.py
- nautobot_ssot/tests/solarwinds/test_solarwinds_adapter.py
- nautobot_ssot/tests/solarwinds/test_utils_solarwinds.py
This PR just fixes the spelling of SolarWinds throughout the App and also removes the note about Arista Labs as the issue has been resolved.
> Correct SolarWinds Naming and Remove Arista Labs Note

- changes/707.fixed
- nautobot_ssot/integrations/slurpit/diffsync/adapters/slurpit.py
Added exception handling to some of the sync functions for slurpit.
> Add exceptions to sync

- changes/705.added
- development/nautobot_config.py
- docs/admin/integrations/bootstrap_setup.md
- docs/user/integrations/bootstrap.md
- nautobot_ssot/integrations/bootstrap/diffsync/adapters/bootstrap.py
- nautobot_ssot/integrations/bootstrap/diffsync/adapters/nautobot.py
- nautobot_ssot/integrations/bootstrap/diffsync/models/base.py
- nautobot_ssot/integrations/bootstrap/diffsync/models/bootstrap.py
- nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
- nautobot_ssot/integrations/bootstrap/fixtures/global_settings.yml
- nautobot_ssot/integrations/bootstrap/signals.py
- nautobot_ssot/tests/bootstrap/fixtures/global_settings.json
- nautobot_ssot/tests/bootstrap/test_nautobot_adapter.py
- nautobot_ssot/tests/bootstrap/test_setup.py
Added support for creating/updating custom_field models into the Bootstrap integration.
> Add custom_field support for Bootstrap integration.

- changes/721.fixed
- nautobot_ssot/integrations/infoblox/signals.py
Updated `source_label` and `destination_label` for Infoblox "Prefix -> VLAN" relationship in order to:
- avoid conflict with `ipam:prefix` model (as described in the issue to resolve)
- make labels more meaningful
> Updated source and destination labels for Infoblox "Prefix -> VLAN" relationship

- changes/737.fixed
- nautobot_ssot/integrations/meraki/diffsync/adapters/meraki.py
- nautobot_ssot/integrations/meraki/utils/meraki.py
- nautobot_ssot/tests/meraki/fixtures/get_org_uplink_addresses_by_device.json
- nautobot_ssot/tests/meraki/test_adapters_meraki.py
This fixes the issue where an AP port isn't loaded properly.
Need to review unit tests and see if I can find some better tests to catch this in the future.
> Fix Loading of AP Ports in Meraki

- changes/743.documentation
- docs/dev/diagrams.md
- mkdocs.yml
This just adds some documentation containing Mermaid diagrams of the models used in SSoT.
> Add Mermaid Diagrams

- changes/767.fixed
- nautobot_ssot/integrations/dna_center/diffsync/adapters/dna_center.py
- nautobot_ssot/integrations/dna_center/diffsync/adapters/nautobot.py
- nautobot_ssot/integrations/dna_center/diffsync/models/base.py
This PR should fix the bug where you have multiple IPAddresses with same host address on an Interface.
> Fix Error Loading IPAddressToInterface In DNA Center

- changes/778.fixed
- nautobot_ssot/integrations/bootstrap/diffsync/models/nautobot.py
Fix update function for Prefix objects when tags or description need to be updated. 
- [ X ] Explanation of Change(s)
- [ X ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ X ] Attached Screenshots, Payload Example
- [ X ] Unit, Integration Tests
- [ X ] Documentation Updates (when adding/changing features)
- [ X ] Outline Remaining Work, Constraints from Design
> Bootstrap prefix update fixes for description and tags

- changes/467.fixed
- nautobot_ssot/integrations/aristacv/diffsync/adapters/cloudvision.py
- nautobot_ssot/integrations/aristacv/diffsync/models/base.py
- nautobot_ssot/integrations/aristacv/diffsync/models/nautobot.py
- nautobot_ssot/integrations/aristacv/utils/cloudvision.py
- nautobot_ssot/tests/aristacv/test_utils_cloudvision.py
This PR is to try to fix the gRPC error being seen when getting devices in the CVP integration.
Still need to finish testing and confirm functionality.
> Fix gRPC Exception in CVP Integration

- changes/822.changed
- nautobot_ssot/jobs/base.py
> disable sorting

- changes/850.added
- nautobot_ssot/__init__.py
- nautobot_ssot/filters.py
This PR adds the ability to search Sync and SyncLogEntries in the global search.
> Make Sync Logs Searchable

- changes/807.fixed
- nautobot_ssot/integrations/meraki/diffsync/adapters/meraki.py
- nautobot_ssot/integrations/meraki/diffsync/adapters/nautobot.py
- nautobot_ssot/integrations/meraki/diffsync/models/base.py
- nautobot_ssot/integrations/meraki/diffsync/models/nautobot.py
- nautobot_ssot/tests/meraki/test_adapters_meraki.py
- nautobot_ssot/tests/meraki/test_adapters_nautobot.py
Turns out that #807 wasn't actually resolved like I thought. There were a few other issues causing problems in this case. I've resolved them all with this PR.
> Redo of Meraki IP Duplication Fix

- changes/916.fixed
- nautobot_ssot/integrations/bootstrap/signals.py
Fixes DLM checking/validation during install of bootstrap integration.
Updated the boolean check for DLM to the recently updated logic for DLM models instead.
> Update bootstrap signal DLM validation

- changes/947.fixed
- nautobot_ssot/filters.py
Import the filters into filters.py. 
Nautobot looks for a filters module within the root of an app based on the locations of the models. Since these models are in the nautobot_ssot.models, it looks for the filters in nautobot_ssot.filters.
Before:
After:
> Import filters from integrations.

- changes/954.housekeeping
- pyproject.toml
This PR updates the target version of Python that ruff is using.
N/A
> Update Python Target Version for Ruff
